# Generated by Django 3.1.5 on 2021-04-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210416_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantilla',
            old_name='title',
            new_name='position',
        ),
    ]
