# Generated by Django 3.1.5 on 2021-04-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210416_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='is_open',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
