# Generated by Django 3.1.5 on 2021-04-20 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210416_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='plantilla_link',
            field=models.ForeignKey(db_column='plantilla_id', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_plantilla', to='employee.plantilla'),
        ),
    ]
