# Generated by Django 3.1.5 on 2021-04-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210420_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'MALE'), (2, 'FEMALE')], default=0),
        ),
    ]
