# Generated by Django 3.1.5 on 2021-04-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210420_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'FIRST'), (2, 'SECOND'), (3, 'RA1080')], default=0),
        ),
    ]
