# Generated by Django 3.1.5 on 2021-04-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210420_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='plantilla_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='plantilla_item',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
