# Generated by Django 3.1.5 on 2021-04-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20210420_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='plantilla_item',
            new_name='plantilla_id',
        ),
    ]
