# Generated by Django 3.1.5 on 2021-04-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20210420_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='plantilla_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
