# Generated by Django 3.1.5 on 2021-04-21 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20210420_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='employee_link',
            field=models.ForeignKey(db_column='employee_id', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantilla_employee', to='employee.employee'),
        ),
    ]
