# Generated by Django 3.1.5 on 2021-05-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210421_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='application_status',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Permanent'), (2, 'Contract of Service')], default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='civil_status',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Single'), (2, 'Married'), (3, 'Widow')], default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'First'), (2, 'Second'), (3, 'RA1080')], default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Male'), (2, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='employeeeducationalbackground',
            name='course',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeeducationalbackground',
            name='date_from',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeeducationalbackground',
            name='date_to',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeeducationalbackground',
            name='graduate_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeeducationalbackground',
            name='scholarship',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeeducationalbackground',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
