# Generated by Django 3.1.5 on 2021-05-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20210514_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducationalbackground',
            name='honor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
