# Generated by Django 3.1.5 on 2021-05-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_auto_20210514_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeligibility',
            name='exam_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeeligibility',
            name='exam_place',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employeeeligibility',
            name='level',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeeligibility',
            name='license_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeeligibility',
            name='license_validity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeeligibility',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
