# Generated by Django 3.1.5 on 2021-04-16 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('nav_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('is_menu', models.BooleanField(default=False)),
                ('is_dropdown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subroute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_nav', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('nav_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=100)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subroute_route', to='authentication.route')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRoute_route', to='authentication.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRoute_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubroute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSubroute_subroute', to='authentication.subroute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSubroute_user', to=settings.AUTH_USER_MODEL)),
                ('user_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSubroute_userRoute', to='authentication.userroute')),
            ],
        ),
    ]
