# Generated by Django 3.1.5 on 2021-05-19 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_auto_20210519_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='GsisPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollGP_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollGP_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateGsisPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('gsis_policy', models.ForeignKey(db_column='gsis_policy_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollTGP_gsis_policy', to='payroll.gsispolicies')),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollTGP_template', to='payroll.template')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollGsisPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('gsis_policy', models.ForeignKey(db_column='gsis_policy_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollPGP_gsis_policy', to='payroll.gsispolicies')),
                ('payroll', models.ForeignKey(db_column='payroll_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollPGP_payroll', to='payroll.payroll')),
            ],
        ),
    ]
