# Generated by Django 3.1.5 on 2021-05-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20210520_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templategsispolicies',
            name='gsis_policy',
        ),
        migrations.RemoveField(
            model_name='templategsispolicies',
            name='template',
        ),
        migrations.DeleteModel(
            name='GsisPolicies',
        ),
        migrations.DeleteModel(
            name='TemplateGsisPolicies',
        ),
    ]
