# Generated by Django 3.1.5 on 2021-05-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20210520_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowances',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
