# Generated by Django 3.1.5 on 2021-05-24 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0016_auto_20210515_0912'),
        ('payroll', '0006_auto_20210520_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(default='', max_length=20)),
                ('station_no', models.CharField(default='', max_length=20)),
                ('fullname', models.CharField(default='', max_length=20)),
                ('position', models.CharField(default='', max_length=200)),
                ('salary_grade', models.PositiveIntegerField(default=0)),
                ('step_increment', models.PositiveIntegerField(default=0)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('plantilla_item', models.CharField(default='', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'N/A'), (1, 'REGULAR'), (2, 'COS')], default=0)),
                ('is_atm', models.BooleanField(default=None, null=True)),
                ('atm_account_no', models.BooleanField(default=None, null=True)),
                ('tin', models.CharField(blank=True, default='', max_length=50)),
                ('gsis', models.CharField(blank=True, default='', max_length=50)),
                ('philhealth', models.CharField(blank=True, default='', max_length=50)),
                ('pagibig', models.CharField(blank=True, default='', max_length=50)),
                ('sss', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollData_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollData_employee', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDataAllowances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDataDeductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(default='', max_length=20)),
                ('station_no', models.CharField(default='', max_length=20)),
                ('fullname', models.CharField(default='', max_length=20)),
                ('position', models.CharField(default='', max_length=200)),
                ('salary_grade', models.PositiveIntegerField(default=0)),
                ('step_increment', models.PositiveIntegerField(default=0)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('plantilla_item', models.CharField(default='', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'N/A'), (1, 'REGULAR'), (2, 'COS')], default=0)),
                ('is_atm', models.BooleanField(default=None, null=True)),
                ('atm_account_no', models.BooleanField(default=None, null=True)),
                ('tin', models.CharField(blank=True, default='', max_length=50)),
                ('gsis', models.CharField(blank=True, default='', max_length=50)),
                ('philhealth', models.CharField(blank=True, default='', max_length=50)),
                ('pagibig', models.CharField(blank=True, default='', max_length=50)),
                ('sss', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templateData_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='templateData_employee', to='employee.employee')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.PROTECT, related_name='templateData_station', to='employee.station')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateDataAllowances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateDataDeductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='payrolldeductions',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='payrolldeductions',
            name='payroll',
        ),
        migrations.RemoveField(
            model_name='templateallowances',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='templateallowances',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templatedeductions',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='templatedeductions',
            name='template',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='atm_account_no',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='employee_no',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='gsis',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='is_atm',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='pagibig',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='philhealth',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='plantilla_item',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='position',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='salary_grade',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='sss',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='station',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='station_no',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='step_increment',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='tin',
        ),
        migrations.RemoveField(
            model_name='template',
            name='atm_account_no',
        ),
        migrations.RemoveField(
            model_name='template',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='template',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='template',
            name='employee_no',
        ),
        migrations.RemoveField(
            model_name='template',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='template',
            name='gsis',
        ),
        migrations.RemoveField(
            model_name='template',
            name='is_atm',
        ),
        migrations.RemoveField(
            model_name='template',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='template',
            name='pagibig',
        ),
        migrations.RemoveField(
            model_name='template',
            name='philhealth',
        ),
        migrations.RemoveField(
            model_name='template',
            name='plantilla_item',
        ),
        migrations.RemoveField(
            model_name='template',
            name='position',
        ),
        migrations.RemoveField(
            model_name='template',
            name='salary_grade',
        ),
        migrations.RemoveField(
            model_name='template',
            name='sss',
        ),
        migrations.RemoveField(
            model_name='template',
            name='station',
        ),
        migrations.RemoveField(
            model_name='template',
            name='station_no',
        ),
        migrations.RemoveField(
            model_name='template',
            name='status',
        ),
        migrations.RemoveField(
            model_name='template',
            name='step_increment',
        ),
        migrations.RemoveField(
            model_name='template',
            name='tin',
        ),
        migrations.AlterField(
            model_name='allowances',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowances_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allowances',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowances_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deductions',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deductions',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='paygroup',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Monthly Regular'), (2, 'Custom')], default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='template',
            name='paygroup',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Monthly Regular'), (2, 'Custom')], default=0),
        ),
        migrations.AlterField(
            model_name='template',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PayrollAllowances',
        ),
        migrations.DeleteModel(
            name='PayrollDeductions',
        ),
        migrations.DeleteModel(
            name='TemplateAllowances',
        ),
        migrations.DeleteModel(
            name='TemplateDeductions',
        ),
        migrations.AddField(
            model_name='templatedatadeductions',
            name='deduction',
            field=models.ForeignKey(db_column='deduction_id', on_delete=django.db.models.deletion.PROTECT, related_name='templateDataDeduc_deduction', to='payroll.deductions'),
        ),
        migrations.AddField(
            model_name='templatedatadeductions',
            name='template_data',
            field=models.ForeignKey(db_column='template_data_id', on_delete=django.db.models.deletion.CASCADE, related_name='templateDataDeduc_templateData', to='payroll.templatedata'),
        ),
        migrations.AddField(
            model_name='templatedataallowances',
            name='allowance',
            field=models.ForeignKey(db_column='allowance_id', on_delete=django.db.models.deletion.PROTECT, related_name='templateDataAllow_allowance', to='payroll.allowances'),
        ),
        migrations.AddField(
            model_name='templatedataallowances',
            name='template_data',
            field=models.ForeignKey(db_column='template_data_id', on_delete=django.db.models.deletion.CASCADE, related_name='templateDataAllow_templateData', to='payroll.templatedata'),
        ),
        migrations.AddField(
            model_name='templatedata',
            name='template',
            field=models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='templateData_template', to='payroll.template'),
        ),
        migrations.AddField(
            model_name='templatedata',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templateData_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolldatadeductions',
            name='deduction',
            field=models.ForeignKey(db_column='deduction_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollDataDeduc_deduction', to='payroll.deductions'),
        ),
        migrations.AddField(
            model_name='payrolldatadeductions',
            name='payroll_data',
            field=models.ForeignKey(db_column='payroll_data_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollDataDeduc_payrollData', to='payroll.payrolldata'),
        ),
        migrations.AddField(
            model_name='payrolldataallowances',
            name='allowance',
            field=models.ForeignKey(db_column='allowance_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollDataAllow_allowance', to='payroll.allowances'),
        ),
        migrations.AddField(
            model_name='payrolldataallowances',
            name='payroll_data',
            field=models.ForeignKey(db_column='payroll_data_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollDataAllow_payrollData', to='payroll.payrolldata'),
        ),
        migrations.AddField(
            model_name='payrolldata',
            name='payroll',
            field=models.ForeignKey(db_column='payroll_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollData_payroll', to='payroll.payroll'),
        ),
        migrations.AddField(
            model_name='payrolldata',
            name='station',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollData_station', to='employee.station'),
        ),
        migrations.AddField(
            model_name='payrolldata',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollData_updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
