# Generated by Django 3.1.5 on 2021-05-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20210524_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolldata',
            name='atm_account_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='templatedata',
            name='atm_account_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
