# Generated by Django 3.1.5 on 2021-05-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20210524_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolldata',
            name='fullname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='templatedata',
            name='fullname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
