# Generated by Django 3.1.5 on 2021-05-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20210515_0912'),
        ('payroll', '0010_auto_20210524_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedata',
            name='station',
            field=models.ForeignKey(db_column='station_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templateData_station', to='employee.station'),
        ),
    ]
