# Generated by Django 3.1.5 on 2021-05-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20210524_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='paygroup',
        ),
        migrations.RemoveField(
            model_name='template',
            name='paygroup',
        ),
        migrations.AddField(
            model_name='payrolldata',
            name='paygroup',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Monthly Regular'), (2, 'Custom')], default=0),
        ),
        migrations.AddField(
            model_name='templatedata',
            name='paygroup',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Monthly Regular'), (2, 'Custom')], default=0),
        ),
    ]
