# Generated by Django 3.1.5 on 2021-05-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_auto_20210524_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolldatadeductions',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='templatedatadeductions',
            name='amount',
        ),
        migrations.AlterField(
            model_name='payrolldata',
            name='paygroup',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Pay with ATM'), (2, 'Pay with Check'), (3, 'COS')], default=0),
        ),
        migrations.AlterField(
            model_name='templatedata',
            name='paygroup',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Pay with ATM'), (2, 'Pay with Check'), (3, 'COS')], default=0),
        ),
    ]
