# Generated by Django 3.1.5 on 2021-05-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_auto_20210524_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolldatadeductions',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='templatedatadeductions',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13),
        ),
    ]
