# Generated by Django 3.1.5 on 2021-05-27 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_auto_20210525_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatedata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='templatedata',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='templatedata',
            name='station',
        ),
        migrations.RemoveField(
            model_name='templatedata',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templatedata',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='templatedataallowances',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='templatedataallowances',
            name='template_data',
        ),
        migrations.RemoveField(
            model_name='templatedatadeductions',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='templatedatadeductions',
            name='template_data',
        ),
        migrations.RenameField(
            model_name='mock',
            old_name='template_id',
            new_name='payroll_id',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='TemplateData',
        ),
        migrations.DeleteModel(
            name='TemplateDataAllowances',
        ),
        migrations.DeleteModel(
            name='TemplateDataDeductions',
        ),
    ]
