# Generated by Django 3.1.5 on 2021-05-27 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20210515_0912'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0017_auto_20210527_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRegular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollRegular_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollRegular_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRegularData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(default='', max_length=20)),
                ('station_no', models.CharField(default='', max_length=20)),
                ('paygroup', models.IntegerField(choices=[(0, 'N/A'), (1, 'Pay with ATM'), (2, 'Pay with Check'), (3, 'COS')], default=0)),
                ('fullname', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('salary_grade', models.PositiveIntegerField(default=0)),
                ('step_increment', models.PositiveIntegerField(default=0)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('plantilla_item', models.CharField(default='', max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'N/A'), (1, 'REGULAR'), (2, 'COS')], default=0)),
                ('is_atm', models.BooleanField(default=None, null=True)),
                ('atm_account_no', models.CharField(default='', max_length=50)),
                ('tin', models.CharField(blank=True, default='', max_length=50)),
                ('gsis', models.CharField(blank=True, default='', max_length=50)),
                ('philhealth', models.CharField(blank=True, default='', max_length=50)),
                ('pagibig', models.CharField(blank=True, default='', max_length=50)),
                ('sss', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollRegularData_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollRegularData_employee', to='employee.employee')),
                ('payroll_regular', models.ForeignKey(db_column='payroll_regular_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollRegularData_payroll', to='payroll.payrollregular')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollRegularData_station', to='employee.station')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollRegularData_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRegularDataAllowances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allowance', models.ForeignKey(db_column='allowance_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollRegularDataAllow_allowance', to='payroll.allowances')),
                ('payroll_data', models.ForeignKey(db_column='payroll_data_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollRegularDataAllow_payrollData', to='payroll.payrollregulardata')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRegularDataDeductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('deduction', models.ForeignKey(db_column='deduction_id', on_delete=django.db.models.deletion.PROTECT, related_name='payrollRegularDataDeduc_deduction', to='payroll.deductions')),
                ('payroll_data', models.ForeignKey(db_column='payroll_data_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollRegularDataDeduc_payrollData', to='payroll.payrollregulardata')),
            ],
        ),
        migrations.RemoveField(
            model_name='payrolldata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payrolldata',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payrolldata',
            name='payroll',
        ),
        migrations.RemoveField(
            model_name='payrolldata',
            name='station',
        ),
        migrations.RemoveField(
            model_name='payrolldata',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='payrolldataallowances',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='payrolldataallowances',
            name='payroll_data',
        ),
        migrations.RemoveField(
            model_name='payrolldatadeductions',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='payrolldatadeductions',
            name='payroll_data',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='PayrollData',
        ),
        migrations.DeleteModel(
            name='PayrollDataAllowances',
        ),
        migrations.DeleteModel(
            name='PayrollDataDeductions',
        ),
    ]
