# Generated by Django 3.1.5 on 2021-05-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_auto_20210527_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollregular',
            name='process_date',
        ),
        migrations.AddField(
            model_name='payrollregular',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payrollregular',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
