# Generated by Django 3.1.5 on 2021-05-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_auto_20210527_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowances',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payrollregulardataallowances',
            name='payroll_data',
        ),
        migrations.RemoveField(
            model_name='payrollregulardatadeductions',
            name='payroll_data',
        ),
        migrations.AddField(
            model_name='payrollregulardataallowances',
            name='payroll_regular_data',
            field=models.ForeignKey(db_column='payroll_regular_data_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payrollRegularDataAllow_payrollRegularData', to='payroll.payrollregulardata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollregulardatadeductions',
            name='payroll_regular_data',
            field=models.ForeignKey(db_column='payroll_regular_data_id', default='', on_delete=django.db.models.deletion.CASCADE, related_name='payrollRegularDataDeduc_payrollRegularData', to='payroll.payrollregulardata'),
            preserve_default=False,
        ),
    ]
