# Generated by Django 3.1.5 on 2021-05-31 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_payrollregular_process_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_id', models.CharField(max_length=50)),
                ('allow1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allow2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allow3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allow4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allow5', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allow6', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allow7', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allow8', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allow9', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
                ('allow10', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13)),
            ],
        ),
        migrations.RenameModel(
            old_name='Mock',
            new_name='MockDeductions',
        ),
        migrations.AlterField(
            model_name='payrollregulardata',
            name='payroll_regular',
            field=models.ForeignKey(db_column='payroll_regular_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollRegularData_payrollRegular', to='payroll.payrollregular'),
        ),
    ]
