# Generated by Django 3.1.5 on 2021-06-02 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_auto_20210531_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(default='', max_length=20)),
                ('field', models.CharField(default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('payroll_regular', models.ForeignKey(db_column='payroll_regular_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollMnt_payrollRegular', to='payroll.payrollregular')),
                ('payroll_regular_data', models.ForeignKey(db_column='payroll_regular_data_id', on_delete=django.db.models.deletion.CASCADE, related_name='payrollMnt_payrollRegularData', to='payroll.payrollregulardata')),
            ],
        ),
    ]
