# Generated by Django 3.1.5 on 2021-06-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_payrollmaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmaintenance',
            name='category',
            field=models.IntegerField(choices=[(0, 'Modified Payroll Data Field'), (1, 'Created Payroll Data'), (2, 'Removed Payroll Data'), (3, 'Modified Deductions'), (4, 'Modified Allowance')], default=0),
        ),
        migrations.AddField(
            model_name='payrollmaintenance',
            name='remarks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
