# Generated by Django 3.1.5 on 2021-06-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_auto_20210602_0255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayrollMaintenance',
            new_name='PayrollRegularMaintenance',
        ),
    ]
