# Generated by Django 3.1.5 on 2021-06-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_auto_20210603_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollregularmaintenance',
            name='amount',
        ),
        migrations.AddField(
            model_name='payrollregularmaintenance',
            name='mod_value',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='payrollregularmaintenance',
            name='category',
            field=models.IntegerField(choices=[(0, 'Modify Field'), (1, 'Create Content'), (2, 'Removed Content')], default=0),
        ),
    ]
