# Generated by Django 3.1.5 on 2021-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20210603_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollregulardata',
            name='paygroup',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Regular'), (2, 'Pay with Check'), (3, 'Actual'), (4, 'COS')], default=0),
        ),
        migrations.AlterField(
            model_name='payrollregularmaintenance',
            name='category',
            field=models.IntegerField(choices=[(1, 'Modify Field'), (2, 'Modify Deductions'), (3, 'Modify Allowance'), (4, 'Create Content'), (4, 'Remove Content')], default=0),
        ),
        migrations.AlterField(
            model_name='payrollregularmaintenance',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
