# Generated by Django 3.1.5 on 2021-06-07 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0028_auto_20210603_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollregularmaintenance',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='payrollMnt_created_by_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollregularmaintenance',
            name='updated_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='payrollMnt_updated_by_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
