# Generated by Django 3.1.5 on 2021-06-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_auto_20210615_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollregulardata',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payrollregularmaintenance',
            name='category',
            field=models.IntegerField(choices=[(1, 'Modify Field'), (2, 'Modify Deductions'), (3, 'Modify Allowance'), (4, 'Create Content'), (5, 'Remove Content')], default=0),
        ),
    ]
