# Generated by Django 3.1.5 on 2021-06-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_auto_20210616_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductions',
            name='priority_seq',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
