# Generated by Django 3.1.5 on 2021-06-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_deductions_priority_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollregularmaintenance',
            name='deduc_priority_seq',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
